In [3]:
#Question 1
from array import * 
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]


In [8]:
#Question 2
import numpy as np
  
# creating a 3X3 Numpy matrix
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the Trace of a matrix
trace = np.trace(n_array)
  
  
print("\nTrace of given 3X3 matrix:")
print(trace)

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Trace of given 3X3 matrix:
176


In [10]:
#Question 3
import numpy as np
x = np.array([[1,2],[3,5]])
print("Original array: ")
print(x)
print("Values bigger than 2 =", x[x>2])

Original array: 
[[1 2]
 [3 5]]
Values bigger than 2 = [3 5]


In [11]:
#Question 4
import numpy as np
 
A = np.array([3, 2, 1])
B = np.array([1, 2, 3])
   
print ("1st array : ", A)  
print ("2nd array : ", B)  
   
C = np.add(A, B)  
print ("added array : ", C) 

1st array :  [3 2 1]
2nd array :  [1 2 3]
added array :  [4 4 4]
